# Generated by Django 3.2.7 on 2021-09-24 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
    ]
